apiVersion: v1
kind: Service
metadata:
  name: nodejs-sample-app
  labels:
    app: nodejs-sample-app
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 5001
  selector:
    app: nodejs-sample-app
